apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-platform-config
  namespace: ops-platform
data:
  DEBUG: "True"
  DB_NAME: "ops_platform_db"
  DB_USER: "ops_user"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  ALLOWED_HOSTS: "*"
