name: Validate K8s Manifests

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check YAML syntax in k8s folder
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yamllint
          yamllint k8s/*.yaml
