name: Validate K8s Manifests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Validate Kubernetes YAML (dry run)
        run: |
          kubectl apply \
            --dry-run=client \
            -f k8s/
