name: Validate K8s Manifests

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Validate each manifest
        run: |
          kubectl apply --dry-run=client --validate=false -f k8s/namespace.yaml
          kubectl apply --dry-run=client --validate=false -f k8s/configmap.yaml
          kubectl apply --dry-run=client --validate=false -f k8s/service.yaml
          kubectl apply --dry-run=client --validate=false -f k8s/deployment.yaml
